namespace VirtualTabGroups.Plugin.Npp
{
    public enum NppMsg : int
    {
        NPPMSG = 0x400 + 1000,

        NPPM_GETFULLCURRENTPATH = NPPMSG + 18,
        NPPM_GETPLUGINSCONFIGDIR = NPPMSG + 46,
        NPPM_DOOPEN = NPPMSG + 77,
        NPPM_GETNBOPENFILES = NPPMSG + 7,
        NPPM_GETOPENFILENAMES = NPPMSG + 8,
        NPPM_GETFULLPATHFROMBUFFERID = NPPMSG + 58,
        NPPM_GETMENUHANDLE = NPPMSG + 25,
        NPPM_MODELESSDIALOG = NPPMSG + 12,
        NPPM_DMMSHOW = NPPMSG + 30,
        NPPM_DMMHIDE = NPPMSG + 31,
        NPPM_DMMUPDATEDISPINFO = NPPMSG + 32,
        NPPM_DMMREGASDCKDLG = NPPMSG + 33,
        NPPM_DMMVIEWOTHERTABBAR = NPPMSG + 35,

        NPPM_ISDARKMODEENABLED = NPPMSG + 107,
        NPPM_GETDARKMODECOLORS = NPPMSG + 108,
        NPPM_DARKMODESUBCLASSANDTHEME = NPPMSG + 112,
    }
}
